sudo: required
language: node_js
node_js:
  - "10.15.3"
services:
  - docker

before_install:
  - docker build -t karimhadja/react-app -f Dockerfile.dev .

scripts:
  - docker run karimhadja/react-app npm run test -- --coverage
